### ISSUE TITLE
[Bug Report] "patchFieldStates" function should sort array items after patching

### ISSUE THREAD

**Issue by ccpu** [alibaba/uform#3220] opened 2022-06-22 17:06 UTC
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-patchfieldstates-issue-forked-37nqhy?file=/App.tsx)

### Steps to reproduce
1. Add first item
2. Enter value in item 1 field
3. Add second item
4. Change item 2 option to 'number'
5. Move option 2 to top with sortable handle
6. Delete moved item (first item from top)
7. Add new item
8. Change new item option to 'number'
9. Enter value in new option field
10. Move new option to top with sortable handle

At this point, the new item value will be lost.

![Animation](https://user-images.githubusercontent.com/4041334/175097059-ccc2c233-3474-4de7-b21b-e9400d17fb55.gif)

### What is expected?
Array items should retain their value after deletion/sorting 

### What is actually happening?
The value of the array items gets lost after being deleted or sorted.

### Package
@formily/core@2.1.6

---
The problem occurs when linked fields have the same object name, but different types. 
Due to the nature of the bug, there may be other unknown problems.

The problem was caused by the [patchFieldStates](https://github.com/alibaba/formily/blob/66ffeb6c5796833bf0491b4328e0c47a334fdada/packages/core/src/shared/internals.ts#L149) function not sorting array items when patching.

So for example assuming the following array items passed to the 'patchFieldStates' function:

array.0.a
array.1.a

After patching the sorted items it will changed to:

array.1.a
array.0.a

And this cause value get lost.

The following code demonstrates how it can be fixed (not very elegant solution):

```js
export const patchFieldStates = (
  target: Record<string, GeneralField>,
  patches: INodePatch<GeneralField>[]
) => {
  patches.forEach(({ type, address, oldAddress, payload }) => {
    if (type === 'remove') {
      destroy(target, address, false)
    } else if (type === 'update') {
      if (payload) {
        target[address] = payload
        if (target[oldAddress] === payload) {
          delete target[oldAddress]
        }
      }
      if (address && payload) {
        locateNode(payload, address)
      }
    }
  })

 // FIX
  const newTarget = Object.keys(target)
    .sort()
    .reduce((obj, key) => {
      obj[key] = target[key]
      delete target[key]
      return obj
    }, {})

  Object.keys(newTarget).forEach((key) => {
    target[key] = newTarget[key]
  })
}
```

**Comment by janryWang** [comment] 2022-06-26 14:56
Sorry, I have been researching this issue for a long time, and I can't figure it out. Can you provide a simpler test case, only use @formily/core, otherwise it will be difficult for me to contact you that the problem is related to patchFieldStates，because sometimes , the problem does not necessarily come from patchFieldStates, just modifying it in patchFieldStates can solve it, but it does not solve the essential problem

**Comment by janryWang** [comment] 2022-06-26 16:34
I am really confused, why not use this way of writing, have to use the field with the same name, and use the hierarchy to hack the value, I do not recommend this way of writing, because it is prone to competition problems, so I will close this issue, If you have any other questions, welcome to the discussion to continue discussing the necessity of this way of writing,Because I haven't found out whether the order of patchFieldStates has bugs in conventional scenarios

```tsx
const schema = {
  properties: {
    array: {
      type: 'array',
      'x-component': 'ArrayItems',
      'x-decorator': 'FormItem',
      items: {
        'x-component': 'Box',
        properties: {
          sort: {
            type: 'void',
            'x-decorator': 'FormItem',
            'x-component': 'ArrayItems.SortHandle',
          },
          A: {
            type: 'void',
            'x-component': 'Box',

            properties: {
              select: {
                enum: [
                  {
                    label: 'string',
                    value: 'string',
                  },
                  {
                    label: 'number',
                    value: 'number',
                  },
                ],
                type: 'string',
                default: 'string',
                'x-component': 'Select',
                'x-decorator': 'FormItem',
                'x-component-props': {
                  style: {
                    width: 120,
                  },
                },
              },
              b: {
                type: 'string',
                'x-component':
                  "{{$record?.select === 'string' ? 'Input' : 'NumberPicker'}}",
                'x-decorator': 'FormItem',
              },
            },
          },
          remove: {
            type: 'void',
            'x-decorator': 'FormItem',
            'x-component': 'ArrayItems.Remove',
          },
        },
        type: 'object',
      },
      properties: {
        add: {
          type: 'void',
          title: 'Add Entry',
          'x-component': 'ArrayItems.Addition',
        },
      },
    },
  },
  type: 'object',
}
```

**Closed as completed by janryWang** 2022-06-26 16:34 UTC

**Comment by ccpu** [comment] 2022-06-28 08:00
> Sorry, I have been researching this issue for a long time, and I can't figure it out. Can you provide a simpler test case, only use @formily/core, otherwise it will be difficult for me to contact you that the problem is related to patchFieldStates，because sometimes , the problem does not necessarily come from patchFieldStates, just modifying it in patchFieldStates can solve it, but it does not solve the essential problem

You are correct, after doing some further digging, I have concluded that the source of the problem is not `patchFieldStates`; the solution I have provided may solve some problems, but not all problems.

**Comment by ccpu** [comment] 2022-06-28 08:02
I agree with your suggestion for the primitive types. We can assign component type directly to the `x-component`:

```js
       'x-component':
                  "{{$record?.select === 'string' ? 'Input' : 'NumberPicker'}}",
```

What if we want to have an `object` instead of `NumberPicker`? The way I did it can be done as follows:

```js
       A: {
            type: "void",
            "x-component": "Box",
            properties: {
              select: {
                enum: [
                  {
                    label: "string",
                    value: "string"
                  },
                  {
                    label: "object",
                    value: "object"
                  }
                ],
                type: "string",
                default: "string",
                "x-component": "Select",
                "x-decorator": "FormItem",
                "x-reactions": `{{()=>{
                  const StringInput = $self.query(".string").take();
                  const NumberInput = $self.query(".object").take();

                  if(StringInput)
                  {
                    StringInput.setDisplay($self.value==="string" ? "visible" : "none");
                  }

                  if(NumberInput)
                  {
                    NumberInput.setDisplay($self.value==="object" ? "visible" : "none");
                  }
                }}}`,
                "x-component-props": {
                  style: {
                    width: 120
                  }
                }
              },
              string: {
                type: "void",
                "x-component": "Box",
                properties: {
                  b: {
                    type: "string",
                    "x-component": "Input",
                    "x-decorator": "FormItem"
                  }
                }
              },
              object: {
                type: "void",
                "x-component": "Box",
                properties: {
                  b: {
                    type: "object",
                    properties: {
                      c: {
                        type: "number",
                        "x-component": "NumberPicker",
                        "x-decorator": "FormItem"
                      }
                    }
                  }
                }
              }
            }
          },
```

Could you suggest a method for this?

**Comment by janryWang** [comment] 2022-06-28 08:17
Dynamic Form Fragments can actually do this. https://formilyjs.org/guide/advanced/controlled
